FUNCTION(INSTALL_TARGETS_CUSTOM)
	message(STATUS "${Magenta}Install targets for ${MODULE_NAME} ... ${ColourReset}")
	if (NAME_EXE)
		message(STATUS "Install tragets EXE : ${Magenta} ${NAME_EXE} ${ColourReset}")
		install(TARGETS ${NAME_EXE} RUNTIME DESTINATION bin)
	endif(NAME_EXE)
	if (NAME_LIB)
		message(STATUS "Install tragets LIB : ${Magenta} ${NAME_LIB} ${ColourReset}")
		install(TARGETS ${NAME_LIB} LIBRARY DESTINATION lib)
	endif(NAME_LIB)
	if (PYTHON_INSTALL_FILES)
		message(STATUS "Install tragets PYTHON : ${Magenta} [${PYTHON_INSTALL_FILES}] ${ColourReset}")
		install(FILES ${PYTHON_INSTALL_FILES} DESTINATION lib)
		install(CODE "execute_process(COMMAND ln -sfv ${CMAKE_INSTALL_PREFIX}/lib/_${MODULE_NAME}${CMAKE_SHARED_LIBRARY_SUFFIX} ${CMAKE_INSTALL_PREFIX}/lib/_${MODULE_NAME}.so)")
	endif(PYTHON_INSTALL_FILES)
ENDFUNCTION(INSTALL_TARGETS_CUSTOM)
