if (CONDA_ENV_ON)
  set(Python_ROOT_DIR $ENV{CONDA_PREFIX})
  message(STATUS "${Green} CONDA ON - Python_ROOT_DIR set to ${Python_ROOT_DIR} ${ColourReset}")
endif()
find_package(Python 3.6 REQUIRED COMPONENTS Interpreter Development NumPy)
if (Python_FOUND)
    message(STATUS "${Green}Python ver. ${Python_VERSION} found.${ColourReset}")
    set(HEPPY_PYTHON_FOUND True)
  else(Python_FOUND)
    message(FATAL_ERROR "${Red}Python not found while it is the key package here...${ColourReset}")
endif(Python_FOUND)
